--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.8) ~  Much Love, Ferib 

]]--

local function v0(v7,v8) return (v7-v8).Magnitude;end local function v1() while true do if autoCollect then local v10={};for v13,v14 in pairs(workspace.Blobs:GetChildren()) do if (v14:IsA("Model") and v14:FindFirstChild("Food")) then local v17=tonumber(v14.Name);if v17 then table.insert(v10,{blob=v14,value=v17});end end end table.sort(v10,function(v15,v16) return v15.value>v16.value ;end);local v11=game.Players.LocalPlayer.Character;local v12=v11 and v11:FindFirstChild("HumanoidRootPart") ;if v12 then for v18,v19 in ipairs(v10) do local v20=v19.blob;local v21=v20:FindFirstChild("Food");if v21 then local v22=true;for v23,v24 in pairs(game.Players:GetPlayers()) do if ((v24~=game.Players.LocalPlayer) and v24.Character) then local v27=v24.Character:FindFirstChild("HumanoidRootPart");if (v27 and (v0(v21.Position,v27.Position)<25)) then v22=false;break;end end end if v22 then local v25=v12.CFrame.Position + Vector3.new(0,50,0) ;v12.CFrame=CFrame.new(v25);v12.CFrame=CFrame.new(v21.CFrame.Position + Vector3.new(0,50,0) );task.wait(0.1);v12.CFrame=v21.CFrame + Vector3.new(0,3,0) ;task.wait(0.2);break;end end end end end task.wait(0.1);end end task.spawn(v1);local v2=loadstring(game:HttpGet("https://raw.githubusercontent.com/Singularity5490/rbimgui-2/main/rbimgui-2.lua"))();local v3=v2.new({text="Auto-Collect Blobs",color=Color3.new(0.2,0.4,0.8)});v3.open();local v4=v3.new({text="Main"});v4.show();local v5=v4.new("folder",{text="Features",color=Color3.new(0.1,0.6,0.1)});v5.open();local v6=v5.new("switch",{text="Enable Auto-Collect",color=Color3.new(0.8,0.2,0.2)});v6.event:Connect(function(v9) autoCollect=v9;print("Auto-Collect is now",(autoCollect and "Enabled") or "Disabled" );end);